### ISSUE TITLE
Horizontal ruler (`<hr/>`) component

### ISSUE THREAD

**Issue by agazso** [snaha-net/diete.design#229]
During building the website I needed a horizontal rule several times and had to implement it for each page. It would be good to add it to the basic components.

Example css:
```css
	hr {
		appearance: none;
		margin-top: var(--double-padding);
		margin-bottom: var(--double-padding);
		border-width: 1px;
		border-style: solid;
		width: 100%;
		color: var(--colors-low);
	}
```
